### ISSUE TITLE
Entering Text on Canvas

### ISSUE THREAD

**Issue by Nightbl927** [timcreatedit/scribble#34]
Great package! Is there a way that we can add text to the drawing canvas like OneNote or Evernote? An ability to put text (non-written) next to what we draw would be very useful.

Additionally, importing of images to overlay on the canvas would be a nice to have also. I can help out if pointed in the right direction.

**Comment by timcreatedit** [comment]
Hi, thanks for the kind words! Adding text or other elements is not in scope for this package, it is intended to be as light as possible, since most usecases won't need these features. 
However, you can always build on the capabilites of scribble to extend the classes and functionalities it provides :)
