### ISSUE TITLE
Sketches could be drawn outside of the scribble widget 

### ISSUE THREAD

**Issue by 2p31-1** [timcreatedit/scribble#35]
![image](https://github.com/timcreatedit/scribble/assets/6959455/f9bc4089-8513-4dfb-b8c9-89d13f52ff40)
The cyan outlined box at right top of the image is the constraint of the scribble widget. But the drawings could be drawn on other widgets when I draw the lines from the box to out of the box. This happens UNEXPECTEDly. It seems that the position of drawing layers gets differ when the size of the widget changes.

So that I tried to delete every dots with listener, but it invokes setState unlimitedly when I try to remove the dots outside of the box via setSketch().

**Comment by Ketul3012** [comment]
+1

**Comment by timcreatedit** [comment]
Hey, thanks for opening an issue! 

I'm sorry it is UNEXPECTED for you, but the way scribble is designed, you are responsible for making sure the size of the sketch is handled, since there is no real way to handle sketch resizing gracefully based on widget sizes (different users might want very different things). 
If you don't care about the lines still being in the sketch data model, you can always wrap Scribble in a `ClipRect` or `ClipRRect` which is not done by default since it might not be necessary depending on usecase and has (slight) performance implications

That being said, the infinite `setState()` calls sound like a potential issue though, could you provide me with more details on how you tried to delete points from the sketch?

**Comment by 2p31-1** [comment]
`ClipRect` works for me. Thanks.
[I tried this](https://github.com/2p31-1/scribble-custom/commit/29c3c25f0ebb30d55f88e68392d167e1a5ff2ee2) to stop drawing on negative x, y position. But it seems that `ClipRect` is more appropriate way to solve it.
