### ISSUE TITLE
Can I add a listener when the drawing is added at onPointerUp?

### ISSUE THREAD

**Issue by 2p31-1** [timcreatedit/scribble#36]
I'm doing a project using several canvases in a screen. I wonder that it is possible to revert or redo the drawing with just a button on several scribble widgets.

Here is the scenario I am expecting:

1. Scribble widgets are in various sized (they're resizable)
<img width="500" alt="제목 없음-2" src="https://github.com/timcreatedit/scribble/assets/6959455/a2b21483-3a2d-4e67-bbd5-d5da6fbafcdb">

2. Drawing lines
<img width="500" alt="2" src="https://github.com/timcreatedit/scribble/assets/6959455/f79682f7-a34a-40c5-9a7c-1a1bf1dbda2c">
<img width="500" alt="3" src="https://github.com/timcreatedit/scribble/assets/6959455/3d878361-9384-4848-83a1-278233161a3e">

3. revert with one button. The stack inside stores the orders of the scribbleNotifier which did drawing or erasing.
<img width="500" alt="4" src="https://github.com/timcreatedit/scribble/assets/6959455/b27a040b-76ad-493e-98ef-263eef257117">

4. reverted in reverse order.
<img width="500" alt="5" src="https://github.com/timcreatedit/scribble/assets/6959455/76d246b6-423c-490f-9a8e-903577bbba0f">

**Comment by timcreatedit** [comment]
Hey there! Thanks for the extensive issue! scribble uses `history_state_notifier` internally for the undo/redo functionality. I would suggest you build your own extension of a `HistoryStateNotifierMixin` that allows for combining multiple `StateNotifier`s together and manage a shared undo/redo state. Since your usecase is very specific, I don't think this is within the scope of this package, but I'm happy to assist you. I will think about adding it to [history_state_notifier](https://github.com/timcreatedit/history_state_notifier), because I think it could be a worthwhile addition to that package (which would also trickle down to scribble), so feel free to open the issue on that repo again!
